name: Terragrunt Workflow

on:
  issue_comment:
    types:
      - created
  pull_request:
    branches:
      - main
    paths:
      - "iac/**"

jobs:
  terragrunt:
    uses: proxmox-home-lab/github-actions/.github/workflows/tpl-terragrunt.yaml@main
    secrets: inherit
