name: Terragrunt Workflow

on:
  issue_comment:
    types:
      - created
  pull_request:
    branches:
      - main
    paths:
      - "iac/**"

jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    uses: proxmox-home-lab/github-actions/.github/workflows/tpl-terragrunt.yaml@main
    secrets: inherit
    with:
      action: plan

  apply:
    if: ${{ github.event_name == 'issue_comment' }}
    uses: proxmox-home-lab/github-actions/.github/workflows/tpl-terragrunt.yaml@main
    secrets: inherit
    with:
      action: apply
