name: Terragrunt Workflow Template

on:
  workflow_call:

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: v0.85.0
          tofu_version: v1.10.5

      - name: Install Vault
        uses: eLco/setup-vault@v1
        with:
          vault_version: 1.20.2

      - name: Run terragrunt plan
        id: terragrunt_plan
        if: github.event_name == 'pull_request'
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_AGENT_CONFIG: ${{ vars.VAULT_AGENT_CONFIG }}
          VAULT_CLIENT_ID: ${{ secrets.VAULT_CLIENT_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          . ./vault-helper.sh
          terragrunt run --all plan --non-interactive --log-level error --working-dir ./iac

      - name: Get terragrunt step id
        id: terragrunt_step_id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          step_url=$(gh run --repo ${{ github.repository }} view ${{ github.run_id }} --json jobs --jq '.jobs[] | select(.name == "${{ github.job }}") | .url, (.steps[] | select(.name == "Run terragrunt plan") | "#step:\(.number):1")' | tr -d "\n")
          echo "step_url=${step_url}" >> $GITHUB_OUTPUT

      - name: PR Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- Terragrunt PR Comment -->
            ## Terragrunt Plan
            Step URL: ${{ steps.terragrunt_step_id.outputs.step_url }}

      - name: Terragrunt Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_AGENT_CONFIG: ${{ vars.VAULT_AGENT_CONFIG }}
          VAULT_CLIENT_ID: ${{ secrets.VAULT_CLIENT_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          source <(curl -s https://raw.githubusercontent.com/proxmox-home-lab/.github/main/vault-helper.sh)
          terragrunt run --all apply --non-interactive --log-level error --working-dir ./iac
